name: graphql-haskell
version: 0.1.0.0
github: "githubuser/graphql-haskell"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2020 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/graphql-haskell#readme>

ghc-options: -Wall
  -fno-warn-name-shadowing
  -Wcompat
  -Wincomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text
  - containers

library:
  source-dirs: src

executables:
  graphql-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - graphql-haskell

tests:
  graphql-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - graphql-haskell
      - hspec
      - hspec-megaparsec
      - raw-strings-qq

benchmarks:
  graphql-haskell-benchmarks:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - graphql-haskell
      - criterion

default-extensions: OverloadedStrings, LambdaCase, TypeFamilies, NoImplicitPrelude
